# Task 1.3 - Math for ML: Worked Solutions

This notebook covers descriptive statistics, probability, linear algebra, 
and basic calculus concepts, connected to their applications in machine learning.

In [1]:
import numpy as np

# --- Descriptive Statistics ---
scores = np.array([85, 90, 78, 92, 88, 76, 95, 89, 84, 91])

mean = np.mean(scores)
median = np.median(scores)
variance = np.var(scores)
std_dev = np.std(scores)

print("Data:", scores)
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance:.2f}")
print(f"Standard Deviation: {std_dev:.2f}")

Data: [85 90 78 92 88 76 95 89 84 91]
Mean: 86.8
Median: 88.5
Variance: 33.36
Standard Deviation: 5.78


**ML Connection:** Mean and standard deviation are the foundation of **feature 
standardization** (`z = (x - mean) / std_dev`), a preprocessing step used in 
almost every ML pipeline to bring features onto a comparable scale before 
training a model. Without this, features with larger numeric ranges can 
dominate distance-based or gradient-based algorithms.

In [2]:
# --- Covariance and Correlation ---
study_hours = np.array([2, 4, 5, 3, 6, 7, 1, 8])
exam_scores = np.array([55, 65, 70, 60, 75, 85, 50, 90])

covariance_matrix = np.cov(study_hours, exam_scores)
correlation_matrix = np.corrcoef(study_hours, exam_scores)

print("Covariance matrix:\n", covariance_matrix)
print("\nCovariance between study_hours and exam_scores:", covariance_matrix[0, 1])
print("\nCorrelation matrix:\n", correlation_matrix)
print("\nCorrelation coefficient:", correlation_matrix[0, 1])

Covariance matrix:
 [[  6.          34.28571429]
 [ 34.28571429 198.21428571]]

Covariance between study_hours and exam_scores: 34.285714285714285

Correlation matrix:
 [[1.         0.99419163]
 [0.99419163 1.        ]]

Correlation coefficient: 0.9941916256019202


**Important Caution:** A correlation of 0.99 does NOT mean study hours *cause* 
higher scores — it only means they move together in this data. Correlation 
never proves causation; a hidden factor (e.g. general discipline) could 
influence both. In ML, this matters because a model can find strong 
correlations that are coincidental or driven by confounding variables, not 
genuine cause-effect relationships.

**ML Connection:** Correlation is used in feature selection — highly 
correlated features often carry redundant information, and checking a 
correlation matrix helps decide which features to keep or drop before 
training a model.

In [1]:
# --- Probability ---
import random

# Simple example: rolling a die, checking conditional probability
outcomes = [1, 2, 3, 4, 5, 6]

# P(even number)
even_numbers = [x for x in outcomes if x % 2 == 0]
p_even = len(even_numbers) / len(outcomes)
print(f"P(even) = {p_even}")

# P(greater than 4)
greater_than_4 = [x for x in outcomes if x > 4]
p_greater_than_4 = len(greater_than_4) / len(outcomes)
print(f"P(greater than 4) = {p_greater_than_4}")

# Independence check: P(even AND greater than 4)
both = [x for x in outcomes if x % 2 == 0 and x > 4]
p_both = len(both) / len(outcomes)
print(f"P(even AND greater than 4) = {p_both}")
print(f"P(even) * P(greater than 4) = {p_even * p_greater_than_4:.3f}")
print("If these two values are equal, the events are independent.")

# Expected value example: a simple weighted average
values = [10, 20, 30]
probabilities = [0.5, 0.3, 0.2]
expected_value = sum(v * p for v, p in zip(values, probabilities))
print(f"\nExpected value = {expected_value}")

P(even) = 0.5
P(greater than 4) = 0.3333333333333333
P(even AND greater than 4) = 0.16666666666666666
P(even) * P(greater than 4) = 0.167
If these two values are equal, the events are independent.

Expected value = 17.0


**ML Connection:** Expected value underlies loss functions — training loss is 
essentially the *expected* error across the dataset. Probability distributions 
also appear directly in classification models, where outputs like softmax 
produce a probability for each class.

In [3]:
# --- Vectors, Matrices, Dot Product ---
import numpy as np
vector_a = np.array([2, 3, 1])
vector_b = np.array([4, 0, 5])

dot_product = np.dot(vector_a, vector_b)
print(f"Vector A: {vector_a}, shape: {vector_a.shape}")
print(f"Vector B: {vector_b}, shape: {vector_b.shape}")
print(f"Dot product: {dot_product}")

# Matrix example
matrix_X = np.array([[1, 2], [3, 4]])
matrix_W = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(matrix_X, matrix_W)
print(f"\nMatrix X:\n{matrix_X}, shape: {matrix_X.shape}")
print(f"Matrix W:\n{matrix_W}, shape: {matrix_W.shape}")
print(f"Matrix product (X . W):\n{matrix_product}")

Vector A: [2 3 1], shape: (3,)
Vector B: [4 0 5], shape: (3,)
Dot product: 13

Matrix X:
[[1 2]
 [3 4]], shape: (2, 2)
Matrix W:
[[5 6]
 [7 8]], shape: (2, 2)
Matrix product (X . W):
[[19 22]
 [43 50]]


**ML Connection:** A single neuron's output is literally a dot product: 
`output = (weights . inputs) + bias`. Every layer in a neural network is a 
matrix multiplication between inputs and weights — this is exactly why 
vector/matrix dimension compatibility is critical when designing networks.

In [4]:
# --- Derivatives and Gradient Descent Intuition ---

def f(x):
    return x**2  # a simple function: loss-like curve

def derivative_f(x):
    return 2*x  # derivative of x^2 is 2x

# Gradient descent: start at a point, move opposite to the gradient
x = 10.0  # starting point (like a bad initial guess)
learning_rate = 0.1

print("Gradient Descent Steps:")
for step in range(10):
    grad = derivative_f(x)
    x = x - learning_rate * grad
    print(f"Step {step+1}: x = {x:.4f}, f(x) = {f(x):.4f}")

print(f"\nFinal x (should be close to 0, the minimum): {x:.4f}")

Gradient Descent Steps:
Step 1: x = 8.0000, f(x) = 64.0000
Step 2: x = 6.4000, f(x) = 40.9600
Step 3: x = 5.1200, f(x) = 26.2144
Step 4: x = 4.0960, f(x) = 16.7772
Step 5: x = 3.2768, f(x) = 10.7374
Step 6: x = 2.6214, f(x) = 6.8719
Step 7: x = 2.0972, f(x) = 4.3980
Step 8: x = 1.6777, f(x) = 2.8147
Step 9: x = 1.3422, f(x) = 1.8014
Step 10: x = 1.0737, f(x) = 1.1529

Final x (should be close to 0, the minimum): 1.0737


**ML Connection:** This tiny loop is the core of how every neural network 
learns. Real training replaces `f(x)=x²` with a loss function over millions 
of parameters, but the idea is identical: compute the gradient, step opposite 
to it, repeat.

## Summary
This notebook covered the four math areas most directly used in ML:
- **Statistics** → feature scaling and understanding data spread
- **Probability** → loss functions and probabilistic model outputs
- **Linear algebra** → how neural network layers compute outputs
- **Calculus** → how models actually learn via gradient descent